#!/usr/bin/env python3
"""Gera os ADRs (docs/adr/NNNN-slug.md) e o índice a partir da lista abaixo.
Os ADRs são o registro curto das decisões estruturais; o raciocínio completo está nos documentos de cada fase.
Uso: python gen_adrs.py   (rodar de dentro de docs/adr)"""
import pathlib
import re

DATE = "2026-10-06"

ADRS = [
 ("Monólito modular em Go",
  "Projeto pessoal, uma pessoa, sem orçamento; a API deve nascer genérica (outros assuntos no futuro).",
  "Um binário Go com módulos `identity`, `catalog`, `learning`, `progress`, `reminders` e biblioteca pura `srs`; cada módulo com `domain/app/adapters`. Um binário, dois papéis (`http`, `worker`).",
  "Deploy simples e depuração fácil; fronteiras precisam ser impostas por ferramenta (ADR 0002). Dividir um módulo quando passar de 60 arquivos.",
  "Microsserviços (custo operacional sem ganho); módulo único sem fronteiras (repetiria o `contracts` de 326 arquivos do Contratos).",
  "fase-3/03-arquitetura-features.md"),
 ("Pacote por funcionalidade e limites medidos no CI",
  "O Contratos tem pastas por tipo técnico (`services/` 53 arquivos, `queries/` 50, `schemas/` 58) e `router.tsx` com 1.278 linhas.",
  "Pacote/pasta por funcionalidade; arquivo ≤ 300 linhas, função ≤ 40 (Go) / 60 (TS), complexidade ≤ 10, ≤ 12 arquivos por pacote Go; `depguard`, `go-arch-lint`, ESLint e `check-structure` reprovam no CI; hook `guard.mjs` bloqueia na edição.",
  "Regras viram código executável, não só texto; custo inicial de configurar as ferramentas.",
  "Só guia escrito (já divergiu no Contratos); só revisão humana.",
  "fase-3/03b-estrutura-pastas.md"),
 ("`srs` como biblioteca pura com Strategy (`simple_v1`, `fsrs6`)",
  "Quero entender e ajustar o algoritmo e poder compará-lo ao FSRS.",
  "Interface `Scheduler{Next, Retrievability}` sem I/O; estratégias registradas por nome; escolha por configuração do usuário. `simple_v1` no MVP, `fsrs6` (go-fsrs v4, MIT) depois.",
  "Testes de propriedade e simulação sem banco; trocar de estratégia = reprocessar o log (ADR 0005).",
  "Só FSRS (menos didático); só regra simples (pior retenção em dados reais, benchmark da comunidade).",
  "fase-1/01-srs.md"),
 ("Domínio (derivado de S) como '% de conhecimento' na UI; R só para fila e notificação",
  "Mostrar R por item cairia sem o usuário agir e desmotivaria; mas R é a probabilidade com sentido estatístico.",
  "Domínio = ln(1+S)/ln(181), alterado só ao responder; R = (1+F·t/S)^-0,1542 calculado na hora; uma curva compartilhada por todas as estratégias. 'Dominado' = S ≥ 90 d.",
  "Dois números a explicar; calibrar S_max = 180 d com dados.",
  "Só R; escore próprio sem modelo de memória.",
  "fase-1/01-srs.md"),
 ("`review_log` imutável e estado derivado por replay",
  "Precisamos re-treinar/otimizar o algoritmo, comparar estratégias e auditar.",
  "Tabela só-INSERT (gatilho bloqueia UPDATE/DELETE), UUID do cliente, estado antes/depois, sugerido × escolhido, scheduler+versão; correção por evento `review_void`.",
  "Armazena mais; exclusão de conta (LGPD) exige rotina controlada e registrada.",
  "Só estado atual (impede replay); eventos em tabela mutável.",
  "fase-1/01-srs.md; fase-3/schema-learning.sql"),
 ("OpenAPI 3.0 primeiro; servidor `oapi-codegen`, cliente `hey-api`",
  "Contrato único sem desvio entre servidor e cliente (no Contratos tipos e serviços são escritos à mão).",
  "`api/openapi/openapi.yaml` é a fonte; Go gerado (`std-http`, modo strict) e TypeScript gerado (tipos, SDK, hooks TanStack Query, Valibot) numa única pasta; CI regenera e falha com diff.",
  "OpenAPI 3.0 (limite do gerador Go); `hey-api` ainda 0.x: versão exata e spike no Sprint 0.",
  "Huma (código-primeiro, OpenAPI 3.1); ogen; clientes escritos à mão.",
  "fase-3/03-arquitetura-features.md; fase-3/openapi-sketch.yaml"),
 ("pgx + sqlc + goose",
  "Quero SQL visível, tipado e migrações simples.",
  "`pgx` v5, consultas em `.sql` compiladas por `sqlc`, migrações com `goose`; transação por Unit of Work no contexto.",
  "Consultas dinâmicas pedem cuidado manual; sem ORM.",
  "GORM (reflexão, comportamento implícito); ent.",
  "fase-3/03-arquitetura-features.md"),
 ("Fila como outbox no PostgreSQL",
  "Envio de push e processamentos assíncronos com idempotência, sem nova infraestrutura.",
  "Tabela `outbox` com `UNIQUE(topic,event_key)`, worker com `FOR UPDATE SKIP LOCKED`, *backoff*, `processed_event` por consumidor.",
  "Throughput limitado ao do Postgres (suficiente); migrar para River (MPL-2.0) se o worker crescer.",
  "RabbitMQ (uma peça a mais para operar); River já agora.",
  "fase-3/03-arquitetura-features.md"),
 ("Eventos em processo; `ReviewCompleted` na mesma transação",
  "Estatísticas (`study_day`) precisam ser consistentes com o log.",
  "Barramento síncrono em memória; handler de `progress` roda antes do commit; integrações externas passam pela outbox.",
  "Acoplamento temporal entre módulos dentro da transação; sem entrega a sistemas externos por este caminho.",
  "Broker externo; eventos assíncronos para tudo.",
  "fase-3/03-arquitetura-features.md"),
 ("Um Keycloak com dois realms (tst e prd)",
  "Identidade pronta (vínculo por e-mail, verificação, MFA); a VM tem 12 GB.",
  "Uma instância do Keycloak (versão fixa por digest) com realms `wordloop-tst` e `wordloop-prd`; PostgreSQL próprio (`keycloak`).",
  "Ponto único de falha para tst e prd e sem ensaio isolado de atualização: exportar realms antes, ensaiar em dev, janela de manutenção. Economiza ~1,25–1,5 GB.",
  "Um Keycloak por ambiente (recomendado, recusado pelo dono); autenticação própria em Go; Authentik/Zitadel.",
  "fase-3/03-arquitetura-features.md (nota de decisões)"),
 ("API como BFF OIDC com cookie `httpOnly`",
  "Evitar tokens no JavaScript (XSS) e simplificar o PWA em mesma origem.",
  "A API faz o fluxo code + PKCE; sessão no PostgreSQL (`auth_session`) com refresh token cifrado; cookie `httpOnly`, `Secure`, `SameSite=Lax`; proteção CSRF por cabeçalho.",
  "~300 linhas de cliente OIDC e sessão por manter; a API deixa de ser só validadora de JWT.",
  "SPA com token em memória; JWT validado na API sem sessão.",
  "fase-3/03-arquitetura-features.md; fase-3/03c-diagramas.md"),
 ("Lembretes por Web Push nativo (VAPID)",
  "Notificação-desafio no celular e no PC, sem custo e sem terceiros nos dados.",
  "`webpush-go` (RFC 8030/8291/8292); assinatura por dispositivo; slots sorteados por dia na janela do usuário; pergunta sem resposta; 404/410 expira; pausa após 3 sem abertura. iPhone só com PWA instalado.",
  "Código próprio de assinatura/envio; limite de ~4 KB no payload; iOS exige instalação e gesto.",
  "OneSignal (terceiro vê usuários e mensagens); ntfy (não é o app do projeto).",
  "fase-3/03-arquitetura-features.md"),
 ("StyleX com Base UI e tokens próprios",
  "Decisão de front já tomada: React + TypeScript + StyleX (0.x).",
  "Tokens `defineVars`/`defineConsts`, temas `createTheme` (claro/escuro/sistema), primitivas Base UI sem estilo + componentes próprios; versões `@stylexjs/*` exatas e atualizadas juntas; ESLint só para StyleX e regras de tamanho.",
  "Ecossistema pequeno; risco de quebra pré-1.0; spike com Vite 8/Vitest 5/React Compiler.",
  "Astryx (beta, só referência por ora); React Aria; componentes 100% próprios.",
  "fase-3/03d-design-system-stylex.md"),
 ("TanStack Router por arquivo e `feature.ts` por `import.meta.glob`",
  "Criar feature no Contratos exige editar `router.tsx`, `i18n.ts` e `nav-items.ts`.",
  "Rotas em `src/routes/` (árvore gerada); menu e namespaces declarados no `feature.ts` da feature; nada central editado à mão.",
  "Arquivo `routeTree.gen.ts` gerado e versionado; rotas finas que importam a feature.",
  "React Router 8 (rotas centrais); manifesto próprio sem roteador de arquivos.",
  "fase-3/03-arquitetura-features.md"),
 ("i18n por namespace carregado sob demanda, com tipos gerados",
  "Textos de interface em pt-BR e en-US; novos idiomas sem mexer em código.",
  "`react-i18next` + `i18next-resources-to-backend`; `locales/<lng>/<ns>.json`; tipos de chave gerados por script; `check:i18n` no CI; hook bloqueia texto literal. O servidor devolve códigos de erro; o front traduz.",
  "Script de geração e checagem a manter.",
  "Lista central de namespaces; tradução de erros no servidor.",
  "fase-3/03-arquitetura-features.md"),
 ("PWA offline com fila idempotente e pacote de estudo local",
  "Estudar sem rede; iOS não tem Background Sync.",
  "`vite-plugin-pwa` (`injectManifest`); pacote de cartões e conteúdo em IndexedDB; revisões com UUID enviadas em lote ao reabrir ou no evento `online`; o servidor refaz correção e nota.",
  "Conflitos entre dispositivos resolvidos por `answered_at`; mais testes.",
  "App só online; Background Sync (indisponível no iOS).",
  "fase-3/03-arquitetura-features.md"),
 ("Monorepo público; `develop` e `main`; merge por squash",
  "Contrato, cliente gerado e deploy mudam juntos; Sonar Free e Actions favorecem repositório público.",
  "`keven-rdr/wordloop`: `api/`, `web/`, `deploy/`, `docs/`, `content/`; PRs para `develop` com título em Conventional Commits; `main` aponta para o que está em prd e é avançada manualmente por fast-forward.",
  "Conteúdo precisa de licença compatível (ADR 0024); `main` depende de disciplina manual.",
  "Dois repositórios; terceiro de infraestrutura; trunk-based puro.",
  "fase-4/04-engenharia.md"),
 ("release-please por componente; build uma vez e promoção por re-etiqueta",
  "O que foi testado em tst deve ser o que roda em prd; sem commit de bot em laço.",
  "release-please em monorepo (`api-vX`, `web-vX`); imagem `sha-<commit>` construída na `develop`; a mesma imagem é re-etiquetada com a versão; tst usa `git describe`.",
  "Tags criadas pelo `GITHUB_TOKEN` não disparam workflows: a promoção fica no mesmo arquivo; atribuição por caminho a validar.",
  "Bump de patch com commit de bot (Contratos); semantic-release; rebuild por ambiente.",
  "fase-4/04-engenharia.md"),
 ("Deploy por SSH com comando forçado e GitHub Environments",
  "VM própria; repositório público torna *runner* self-hosted arriscado.",
  "Workflow reutilizável chama `deploy.sh` por chave com `command=`; Environment `prd` com revisor obrigatório e restrição a tags; rollback = redeploy da tag anterior; migrações expand/contract.",
  "SSH exposto (só chave, `fail2ban`); estado das tags fica na VM e no histórico de deploys do GitHub.",
  "Runner self-hosted; commit de bot com tag no overlay; k3s + Argo CD.",
  "fase-4/04-engenharia.md; fase-4/deploy/deploy-skeleton.md"),
 ("Docker Compose em uma VM Contabo: três projetos, um Postgres, Caddy",
  "Orçamento mínimo; ambientes tst e prd na mesma VM.",
  "Projetos `shared` (Caddy, PostgreSQL com 3 bancos, Keycloak), `tst` e `prd`; só o Caddy publica portas; configuração em runtime (`environment.json`); imagens por tag+digest; backup `pg_dump`+`age` para o Cloudflare R2.",
  "VM única é ponto único de falha; tst e prd compartilham o servidor de banco.",
  "Kubernetes leve; um Postgres por ambiente.",
  "fase-4/deploy/deploy-skeleton.md"),
 ("SonarQube Cloud Free com `develop` como branch principal",
  "O plano Free analisa PR e branch só da branch principal e não personaliza o quality gate.",
  "Dois projetos (`api`, `web`) no Sonar; `develop` como principal; token só por secret; o que o Sonar não cobre é imposto pelo CI e pelo hook.",
  "PRs de release (`develop → main`) não são analisadas.",
  "SonarQube self-hosted (sem análise de branch/PR e pesado); um projeto único.",
  "fase-4/04-engenharia.md"),
 ("Imagens: OpenMoji como base, fora do Git, com manifesto de licença",
  "Repositório público; Pexels/Pixabay vetam redistribuição avulsa e o Unsplash exige hotlink.",
  "OpenMoji (CC BY-SA 4.0) e Commons filtrado; arquivos em volume fora do Git; tabela `media` com hash, licença, crédito e `status`; imagem aparece depois da tentativa e some com S ≥ 21 d.",
  "Estilo emoji pode parecer infantil (testar no Sprint 1); conteúdo derivado vira CC BY-SA.",
  "Pexels/Pixabay/Unsplash; IA generativa agora.",
  "fase-2/02-pedagogia-conteudo.md"),
 ("Cobertura de vocabulário por texto como métrica de leitura",
  "Compreensão de leitura depende da porcentagem de palavras conhecidas.",
  "Lema conhecido = receptivo em review com S ≥ 7 d; ≥ 95% libera leitura guiada, ≥ 98% leitura livre; textos graduados (curadoria + geração offline validada por script).",
  "Cobertura por lema ignora sentidos no MVP.",
  "Contagem bruta de palavras; só nível CEFR.",
  "fase-2/02-pedagogia-conteudo.md"),
 ("Licenças: código MIT e conteúdo CC BY-SA 4.0",
  "App aberto, sem fins lucrativos; conteúdo derivado de NGSL e OpenMoji (Share-Alike).",
  "`LICENSE` MIT na raiz; `content/` e dumps em CC BY-SA 4.0 com `NOTICE.md` gerado de `source`/`attribution`; checagem de licença no CI.",
  "Quem reutilizar o conteúdo deve compartilhar adaptações; revisar compatibilidade de Tatoeba CC BY 2.0 FR e Wiktionary. Não é aconselhamento jurídico.",
  "Tudo MIT (viola Share-Alike); conteúdo proprietário.",
  "fase-2/02-pedagogia-conteudo.md; fase-4/04-engenharia.md"),
 ("Kit de instruções para IA: `AGENTS.md` canônico, hook e skill",
  "No Contratos há três arquivos de instrução sobrepostos e já divergentes.",
  "`AGENTS.md` (raiz, `api/`, `web/`) com regras obrigatórias e precedência; `CLAUDE.md` só importa; hook `PreToolUse` bloqueia `.env*`, código gerado, arquivos grandes, texto de UI e cor crua; skill `wl-flow` com gates; PR template e documento vivo.",
  "Instrução é contexto, não garantia: o que não pode acontecer vai para hook e CI.",
  "Três arquivos paralelos; só revisão humana.",
  "fase-4/04-engenharia.md; fase-4/kit-ia/"),
 ("Experiência: sem XP, ranking nem mascote; sequência por revisão; barra de 4 itens",
  "Meta é motivar a voltar e melhorar, não cumprir minutos; sem culpa.",
  "Progresso = palavras conhecidas e cobertura; sequência = ≥ 1 revisão e dias fora da meta não quebram; sons desligados por padrão; barra inferior com Início, Estudar, Palavras e Mais, e 'Ler' só quando houver texto liberado.",
  "Pode ter menos apelo que apps com pontos: validar no teste de usabilidade.",
  "XP e ligas; barra de 5 itens com 'Ler' sempre visível (recusada pelo dono).",
  "fase-5/05-ux-ui-fluxos.md"),
]


def slug(t: str) -> str:
    s = re.sub(r"[`'()·]", "", t.lower())
    s = (s.replace("ã", "a").replace("á", "a").replace("â", "a").replace("é", "e").replace("ê", "e")
          .replace("í", "i").replace("ó", "o").replace("õ", "o").replace("ô", "o").replace("ú", "u").replace("ç", "c"))
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s if len(s) <= 50 else s[:50].rsplit("-", 1)[0]


def main() -> None:
    here = pathlib.Path(__file__).parent
    index = ["# ADRs — registro de decisões estruturais", "",
             f"Gerados por `gen_adrs.py` em {DATE}. Cada ADR é curto; o raciocínio completo está no documento da fase indicado.", "",
             "| # | Decisão | Fonte |", "|---|---|---|"]
    for n, (title, ctx, dec, cons, alt, src) in enumerate(ADRS, 1):
        name = f"{n:04d}-{slug(title)}.md"
        body = (f"# ADR {n:04d} — {title}\n\n**Status:** aceita ({DATE})\n\n## Contexto\n{ctx}\n\n## Decisão\n{dec}\n\n"
                f"## Consequências\n{cons}\n\n## Alternativas descartadas\n{alt}\n\n## Fonte\n`docs/{src}`\n")
        (here / name).write_text(body, encoding="utf-8")
        index.append(f"| {n:04d} | [{title}]({name}) | `{src}` |")
    (here / "README.md").write_text("\n".join(index) + "\n", encoding="utf-8")
    print(f"{len(ADRS)} ADRs gerados")


if __name__ == "__main__":
    main()
